version: '3.8'
services:
  kameleon_machine:
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    deploy:
      replicas: 1
    networks:
      machine-net:
        ipv4_address: 192.168.55.2
    volumes:
      - ./main.py:/kameleon/main.py
      - ./extensions_handler.py:/kameleon/extensions_handler.py
      - ./ansible_wrapper:/kameleon/ansible_wrapper
      - ./web:/kameleon/web
      - ./configuration:/kameleon/configuration
      - ./connectors:/kameleon/connectors
      - ./data_management:/kameleon/data_management
      - ./db:/kameleon/db
      - ./extensions:/kameleon/extensions
      - ./host_management:/kameleon/host_management
      - ./templates:/kameleon/templates
      - ./static:/kameleon/static
      - ./configuration.yaml:/kameleon/configuration.yaml
      - ./env:/kameleon/env
      - ./ansible_wrapper/playbooks:/kameleon/ansible_wrapper/playbooks
      - ./core:/kameleon/core
      - ./inventory:/kameleon/inventory
    ports:
      - "127.0.0.1:5000:5000"

  keycloak:
    # http://localhost:8080/admin/master/console/
    image: quay.io/keycloak/keycloak:latest
    networks:
      machine-net:
        ipv4_address: 192.168.55.222
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_LOG_LEVEL_ORG_KEYCLOAK=ERROR # Set log level to ERROR
    ports:
      - "8080:8080" # Expose Keycloak on port 8080
    volumes:
      - ./kameleon-realm.json:/opt/keycloak/data/import/kameleon-realm.json # Mount realm JSON file
    entrypoint: "/opt/keycloak/bin/kc.sh start-dev --import-realm"

  agent_machine_1:
    build:
      context: .
      dockerfile: docker/target_host.Dockerfile
    deploy:
      replicas: 1
    networks:
      machine-net:
        ipv4_address: 192.168.55.3
    volumes:
      - ./agent:/kameleon-agent/
      - ./core:/kameleon-agent/core

  agent_machine_2:
    build:
      context: .
      dockerfile: docker/target_host.Dockerfile
    deploy:
      replicas: 1
    networks:
      machine-net:
        ipv4_address: 192.168.55.4
    volumes:
      - ./agent:/kameleon-agent/
      - ./core:/kameleon-agent/core
  agent_machine_da_1:
    build:
      context: .
      dockerfile: docker/target_host_with_da_files.Dockerfile
    deploy:
      replicas: 1
    networks:
      machine-net:
        ipv4_address: 192.168.55.5
    volumes:
      - ./agent:/kameleon-agent/
      - ./core:/kameleon-agent/core
  agent_machine_da_2:
    build:
      context: .
      dockerfile: docker/target_host_with_da_files.Dockerfile
    deploy:
      replicas: 1
    networks:
      machine-net:
        ipv4_address: 192.168.55.6
    volumes:
      - ./agent:/kameleon-agent/
      - ./core:/kameleon-agent/core

networks:
  machine-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "192.168.55.0/24"
