version: '3.8'
services:
  kameleon_machine:
    build:
      context: .
      dockerfile: docker/app.Dockerfile
    deploy:
      replicas: 1
    networks:
      machine-net:
        ipv4_address: 192.168.55.2
    volumes:
      - ./main.py:/kameleon/main.py
      - ./extensions_handler.py:/kameleon/extensions_handler.py
      - ./ansible_wrapper:/kameleon/ansible_wrapper
      - ./api:/kameleon/api
      - ./configuration:/kameleon/configuration
      - ./connectors:/kameleon/connectors
      - ./data_management:/kameleon/data_management
      - ./db:/kameleon/db
      - ./extensions:/kameleon/extensions
      - ./host_management:/kameleon/host_management
      - ./templates:/kameleon/templates
      - ./static:/kameleon/static
      - ./configuration.yaml:/kameleon/configuration.yaml
      - ./env:/kameleon/env
      - ./ansible_wrapper/playbooks:/kameleon/ansible_wrapper/playbooks
    ports:
      - "127.0.0.1:5000:5000"

  agent_machine_1:
    build:
      context: .
      dockerfile: docker/target_host.Dockerfile
    deploy:
      replicas: 1
    networks:
      machine-net:
        ipv4_address: 192.168.55.3
    volumes:
      - ./agent:/kameleon-agent/

  agent_machine_2:
    build:
      context: .
      dockerfile: docker/target_host.Dockerfile
    deploy:
      replicas: 1
    networks:
      machine-net:
        ipv4_address: 192.168.55.4
    volumes:
      - ./agent:/kameleon-agent/

  agent_machine_3:
    build:
      context: .
      dockerfile: docker/target_host.Dockerfile
    deploy:
      replicas: 1
    networks:
      machine-net:
        ipv4_address: 192.168.55.5
    volumes:
      - ./agent:/kameleon-agent/

networks:
  machine-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "192.168.55.0/24"